/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Pricing {
  'teamSize' : bigint,
  'cost' : bigint,
  'time' : bigint,
}
export interface Truck {
  'status' : TruckStatus,
  'number' : bigint,
  'location' : string,
}
export type TruckStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'inTransit' : null };
export interface _SERVICE {
  'getAllTruckStatuses' : ActorMethod<[], Array<Truck>>,
  'getEstimate' : ActorMethod<[string], Pricing>,
  'setupDefaultConfig' : ActorMethod<[], undefined>,
  'updatePricingConfig' : ActorMethod<
    [string, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];