/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TruckStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'inTransit' : IDL.Null,
});
export const Truck = IDL.Record({
  'status' : TruckStatus,
  'number' : IDL.Nat,
  'location' : IDL.Text,
});
export const Pricing = IDL.Record({
  'teamSize' : IDL.Nat,
  'cost' : IDL.Nat,
  'time' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllTruckStatuses' : IDL.Func([], [IDL.Vec(Truck)], ['query']),
  'getEstimate' : IDL.Func([IDL.Text], [Pricing], ['query']),
  'setupDefaultConfig' : IDL.Func([], [], []),
  'updatePricingConfig' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TruckStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'inTransit' : IDL.Null,
  });
  const Truck = IDL.Record({
    'status' : TruckStatus,
    'number' : IDL.Nat,
    'location' : IDL.Text,
  });
  const Pricing = IDL.Record({
    'teamSize' : IDL.Nat,
    'cost' : IDL.Nat,
    'time' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllTruckStatuses' : IDL.Func([], [IDL.Vec(Truck)], ['query']),
    'getEstimate' : IDL.Func([IDL.Text], [Pricing], ['query']),
    'setupDefaultConfig' : IDL.Func([], [], []),
    'updatePricingConfig' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };